# Generated by Django 4.0.5 on 2022-06-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='archive_flag',
            new_name='archived',
        ),
    ]
